# Generated by Django 4.0.2 on 2022-02-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategory_alter_product_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
