# Generated by Django 4.0.2 on 2022-02-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_created_at_product_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
