# Generated by Django 4.0.2 on 2022-02-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update_time',
            new_name='update_at',
        ),
    ]
