# Generated by Django 4.0.2 on 2022-02-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_alter_order_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
