# Generated by Django 4.0.2 on 2022-02-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket1',
            old_name='ticket_name',
            new_name='ticket_title',
        ),
    ]
