# Generated by Django 4.0.2 on 2022-03-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=50)),
                ('fruit', models.CharField(choices=[('apple', 'apple'), ('banana', 'banana'), ('orange', 'orange'), ('grapes', 'grapes'), ('berry', 'berry')], max_length=50)),
            ],
            options={
                'db_table': 'season',
            },
        ),
    ]
