# Generated by Django 4.0.2 on 2022-02-14 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'depart',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_name', models.CharField(max_length=50)),
                ('rol_description', models.TextField()),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('Depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.depart')),
            ],
            options={
                'db_table': 'emp',
            },
        ),
        migrations.AddField(
            model_name='depart',
            name='Rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.rol'),
        ),
    ]
